---
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not use
# this file except in compliance with the License. A copy of the License is
# located at
#
# http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
version: 0.2

env:
  variables:
    # CODEBUILD_ is a reserved namespace.
    CB_BIN_DIR: "./codebuild/bin"
    CB_SPEC_DIR: "./codebuild/spec" #These only worn on command lines.

# Prove that:
# 1. build-list can call another buildspec file w/o running the commands in this buildspec
# 2. review the naming of the sub-jobs, does the identifier get chopped?
# 3. will this generally work as a model?
batch:
  build-list:
    - identifier: asan_openssl111_coverage
      env:
        variables:
          TESTS: asan
          GCC_VERSION: '6'
          S2N_LIBCRYPTO: 'openssl-1.1.1'
          BUILD_S2N: 'true'
          S2N_COVERAGE: 'false'
          CODECOV_IO_UPLOAD: 'false'
          CODECOV_TOKEN: 'foobar'

    - identifier: asan_openssl102
      env:
        variables:
          TESTS: asan
          GCC_VERSION: '6'
          S2N_LIBCRYPTO: 'openssl-1.0.2'
          BUILD_S2N: 'true'

    - identifier: valgrind_openssl102
      env:
        variables:
          TESTS: valgrind
          GCC_VERSION: '6'
          S2N_LIBCRYPTO: 'openssl-1.0.2'
          BUILD_S2N: 'true'

    - identifier: integ_boringlibre
      buildspec: codebuild/spec/buildspec_ubuntu_integ_boringlibre.yml

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo S2N_LIBCRYPTO=$S2N_LIBCRYPTO GCC_VERSION=$GCC_VERSION $CB_BIN_DIR/install_default_dependencies.sh
  build:
    commands:
      - printenv
      - echo S2N_LIBCRYPTO=$S2N_LIBCRYPTO GCC_VERSION=$GCC_VERSION $CB_BIN_DIR/s2n_codebuild.sh
  post_build:
    commands:
      - echo Build completed on `date`
